# coding: utf-8

"""
    backend service

    Сервис для управления ПВЗ и приемкой товаров

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from src.endpoints.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="backend service",
    description="Сервис для управления ПВЗ и приемкой товаров",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)

import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)

logger = logging.getLogger(__name__)

