# coding: utf-8

"""
    backend service

    Сервис для управления ПВЗ и приемкой товаров

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel
from typing import Any, ClassVar, Dict, List, Optional
from src.endpoints.models.product import Product
from src.endpoints.models.reception import Reception
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PvzGet200ResponseInnerReceptionsInner(BaseModel):
    """
    PvzGet200ResponseInnerReceptionsInner
    """ # noqa: E501
    reception: Optional[Reception] = None
    products: Optional[List[Product]] = None
    __properties: ClassVar[List[str]] = ["reception", "products"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PvzGet200ResponseInnerReceptionsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of reception
        if self.reception:
            _dict['reception'] = self.reception.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in products (list)
        _items = []
        if self.products:
            for _item in self.products:
                if _item:
                    _items.append(_item.to_dict())
            _dict['products'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PvzGet200ResponseInnerReceptionsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reception": Reception.from_dict(obj.get("reception")) if obj.get("reception") is not None else None,
            "products": [Product.from_dict(_item) for _item in obj.get("products")] if obj.get("products") is not None else None
        })
        return _obj


