# coding: utf-8

"""
    backend service

    Сервис для управления ПВЗ и приемкой товаров

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel
from typing import Any, ClassVar, Dict, List, Optional
from src.endpoints.models.pvz import PVZ
from src.endpoints.models.pvz_get200_response_inner_receptions_inner import PvzGet200ResponseInnerReceptionsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PvzGet200ResponseInner(BaseModel):
    """
    PvzGet200ResponseInner
    """ # noqa: E501
    pvz: Optional[PVZ] = None
    receptions: Optional[List[PvzGet200ResponseInnerReceptionsInner]] = None
    __properties: ClassVar[List[str]] = ["pvz", "receptions"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PvzGet200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pvz
        if self.pvz:
            _dict['pvz'] = self.pvz.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in receptions (list)
        _items = []
        if self.receptions:
            for _item in self.receptions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['receptions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PvzGet200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pvz": PVZ.from_dict(obj.get("pvz")) if obj.get("pvz") is not None else None,
            "receptions": [PvzGet200ResponseInnerReceptionsInner.from_dict(_item) for _item in obj.get("receptions")] if obj.get("receptions") is not None else None
        })
        return _obj


